package export

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixtureKnowledge builds a knowledge dir with one global agent, one global
// skill (with attachment), and one repo-scoped skill that must stay local.
func fixtureKnowledge(t *testing.T) string {
	t.Helper()
	kdir := t.TempDir()
	files := map[string]string{
		"agents/reviewer.md": `---
title: reviewer
summary: reviews code
export:
  kind: agent
  name: reviewer
  frontmatter: |-
    name: reviewer
    description: reviews code
---

Review the code carefully.
`,
		"skills/commit/SKILL.md": `---
title: commit
summary: makes commits
export:
  kind: skill
  name: commit
  frontmatter: |-
    description: makes commits
  attachments:
    - templates.md
---

Commit skill body.
`,
		"skills/commit/templates.md": "template content\n",
		"skills/local/SKILL.md": `---
title: local
summary: repo-only skill
scope: [repo:alpha]
export:
  kind: skill
  name: local
  frontmatter: |-
    description: repo-only
---

Stays local.
`,
	}
	for rel, content := range files {
		path := filepath.Join(kdir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return kdir
}

func TestExportGeneratesAndConverges(t *testing.T) {
	kdir := fixtureKnowledge(t)
	target := t.TempDir()
	statePath := filepath.Join(t.TempDir(), "manifest.json")

	res, err := Run(kdir, target, statePath, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Written) != 3 { // agent + skill + attachment
		t.Errorf("written = %v", res.Written)
	}
	if len(res.Skipped) != 1 || !strings.Contains(res.Skipped[0], "repo:alpha") {
		t.Errorf("skipped = %v", res.Skipped)
	}
	raw, err := os.ReadFile(filepath.Join(target, "agents", "reviewer.md"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(raw)
	if !strings.HasPrefix(got, "---\nname: reviewer\n") {
		t.Errorf("frontmatter not replayed:\n%s", got)
	}
	if !strings.Contains(got, "GENERATED by culi") || !strings.Contains(got, "Review the code carefully.") {
		t.Errorf("header/body missing:\n%s", got)
	}
	if _, err := os.Stat(filepath.Join(target, "skills", "commit", "templates.md")); err != nil {
		t.Errorf("attachment not exported: %v", err)
	}
	// Second run converges to a no-op.
	res, err = Run(kdir, target, statePath, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if res.Drifted() {
		t.Errorf("second run not converged: %+v", res)
	}
	// --check agrees.
	if res, err = Run(kdir, target, statePath, true, false); err != nil || res.Drifted() {
		t.Errorf("check after converge: %+v err=%v", res, err)
	}
}

func TestExportProtectsHandEdits(t *testing.T) {
	kdir := fixtureKnowledge(t)
	target := t.TempDir()
	statePath := filepath.Join(t.TempDir(), "manifest.json")
	if _, err := Run(kdir, target, statePath, false, false); err != nil {
		t.Fatal(err)
	}
	edited := filepath.Join(target, "agents", "reviewer.md")
	if err := os.WriteFile(edited, []byte("my precious edits\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	res, err := Run(kdir, target, statePath, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Edited) != 1 || res.Edited[0] != "agents/reviewer.md" {
		t.Errorf("edited = %v", res.Edited)
	}
	if raw, _ := os.ReadFile(edited); string(raw) != "my precious edits\n" {
		t.Error("hand edit clobbered")
	}
	// check mode sees the drift without writing anything.
	res, err = Run(kdir, target, statePath, true, false)
	if err != nil {
		t.Fatal(err)
	}
	if !res.Drifted() {
		t.Error("check misses hand edit")
	}
	// force re-asserts the generated content.
	if _, err := Run(kdir, target, statePath, false, true); err != nil {
		t.Fatal(err)
	}
	if raw, _ := os.ReadFile(edited); !strings.Contains(string(raw), "GENERATED by culi") {
		t.Error("force did not regenerate")
	}
}

func TestExportRemovesStale(t *testing.T) {
	kdir := fixtureKnowledge(t)
	target := t.TempDir()
	statePath := filepath.Join(t.TempDir(), "manifest.json")
	if _, err := Run(kdir, target, statePath, false, false); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Join(kdir, "agents", "reviewer.md")); err != nil {
		t.Fatal(err)
	}
	res, err := Run(kdir, target, statePath, false, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Removed) != 1 || res.Removed[0] != "agents/reviewer.md" {
		t.Errorf("removed = %v", res.Removed)
	}
	if _, err := os.Stat(filepath.Join(target, "agents", "reviewer.md")); !os.IsNotExist(err) {
		t.Error("stale file still present")
	}
	// A pre-existing file culi never wrote is untouchable even when stale
	// logic runs: simulate by planting an unmanifested file — export must
	// leave it alone entirely.
	foreign := filepath.Join(target, "agents", "mine.md")
	if err := os.WriteFile(foreign, []byte("user's own agent\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Run(kdir, target, statePath, false, false); err != nil {
		t.Fatal(err)
	}
	if raw, _ := os.ReadFile(foreign); string(raw) != "user's own agent\n" {
		t.Error("foreign file touched")
	}
}
