// Package export regenerates ~/.claude/agents and ~/.claude/skills from
// canonical cards, so Claude Code merges them into every repo natively and
// per-repo copies can be deleted. A hash manifest of everything culi wrote
// makes hand-edits detectable: export never clobbers a file it cannot prove
// it generated (contract C4).
package export

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/hung12ct/culi/internal/knowledge"
)

// Result reports one export (or check) run.
type Result struct {
	Written []string // files created or refreshed (would-be, in check mode)
	Removed []string // stale generated files deleted (would-be, in check mode)
	Edited  []string // hand-edited generated files — never touched
	Skipped []string // export cards not exported (non-global scope), with reason
}

// Drifted reports whether the target dir disagrees with what export would
// produce — the --check exit condition.
func (r Result) Drifted() bool { return len(r.Written)+len(r.Removed)+len(r.Edited) > 0 }

// manifest maps target-relative paths to the sha256 culi last wrote there.
type manifest map[string]string

// Run generates targetDir (usually ~/.claude) from export-capable global
// cards in knowledgeDir. check reports without writing; force overwrites even
// hand-edited files.
func Run(knowledgeDir, targetDir, statePath string, check, force bool) (Result, error) {
	var res Result
	want, err := desiredFiles(knowledgeDir, &res)
	if err != nil {
		return res, err
	}
	man, err := readManifest(statePath)
	if err != nil {
		return res, err
	}

	for _, rel := range sortedKeys(want) {
		status := fileStatus(filepath.Join(targetDir, rel), rel, want[rel], man)
		switch {
		case status == upToDate:
			continue
		case status == handEdited && !force:
			res.Edited = append(res.Edited, rel)
			continue
		}
		res.Written = append(res.Written, rel)
		if check {
			continue
		}
		if err := writeAtomic(filepath.Join(targetDir, rel), want[rel]); err != nil {
			return res, err
		}
		man[rel] = hashOf(want[rel])
	}

	for _, rel := range sortedKeys(man) {
		if _, still := want[rel]; still {
			continue
		}
		path := filepath.Join(targetDir, rel)
		switch st := staleStatus(path, man[rel]); {
		case st == upToDate: // unmodified generated file, card gone → remove
			res.Removed = append(res.Removed, rel)
			if !check {
				_ = os.Remove(path)
				delete(man, rel)
			}
		case st == handEdited && !force:
			res.Edited = append(res.Edited, rel)
		case st == handEdited: // force
			res.Removed = append(res.Removed, rel)
			if !check {
				_ = os.Remove(path)
				delete(man, rel)
			}
		default: // already gone
			if !check {
				delete(man, rel)
			}
		}
	}

	if !check {
		if err := writeManifest(statePath, man); err != nil {
			return res, err
		}
	}
	return res, nil
}

// desiredFiles renders every exportable card (and skill attachments) into the
// target-relative file map.
func desiredFiles(knowledgeDir string, res *Result) (map[string][]byte, error) {
	files, err := knowledge.Walk(knowledgeDir)
	if err != nil {
		return nil, fmt.Errorf("export: %w", err)
	}
	want := map[string][]byte{}
	for _, f := range files {
		card, err := knowledge.ReadCard(knowledgeDir, f.RelPath)
		if err != nil || card.Export == nil {
			continue // unparseable files are the indexer's problem to report
		}
		if !slices.Contains(card.Scopes, "global") {
			res.Skipped = append(res.Skipped, fmt.Sprintf("%s: scope %v stays in its repo", card.ID, card.Scopes))
			continue
		}
		rel, content, err := renderArtifact(card)
		if err != nil {
			return nil, err
		}
		want[rel] = content
		for _, att := range card.Export.Attachments {
			src := filepath.Join(knowledgeDir, filepath.Dir(filepath.FromSlash(f.RelPath)), filepath.FromSlash(att))
			raw, err := os.ReadFile(src)
			if err != nil {
				return nil, fmt.Errorf("export: reading attachment %s: %w", src, err)
			}
			want[filepath.ToSlash(filepath.Join(filepath.Dir(rel), filepath.FromSlash(att)))] = raw
		}
	}
	return want, nil
}

// renderArtifact rebuilds the Claude Code file for a card: original
// frontmatter verbatim, a GENERATED header, then the body.
func renderArtifact(card knowledge.Card) (rel string, content []byte, err error) {
	switch card.Export.Kind {
	case "agent":
		rel = "agents/" + card.Export.Name + ".md"
	case "skill":
		rel = "skills/" + card.Export.Name + "/SKILL.md"
	default:
		return "", nil, fmt.Errorf("export: card %s: unknown export kind %q", card.ID, card.Export.Kind)
	}
	var b strings.Builder
	if fm := strings.TrimSpace(card.Export.Frontmatter); fm != "" {
		b.WriteString("---\n")
		b.WriteString(fm)
		b.WriteString("\n---\n\n")
	}
	fmt.Fprintf(&b, "<!-- GENERATED by culi from card %s — edit the card, then run `culi export`. -->\n\n", card.ID)
	b.WriteString(card.Body)
	if !strings.HasSuffix(card.Body, "\n") {
		b.WriteByte('\n')
	}
	return rel, []byte(b.String()), nil
}

type status int

const (
	upToDate status = iota
	needsWrite
	handEdited
	missing
)

// fileStatus compares a target file against the desired content and manifest.
// A file culi never wrote (absent from manifest) counts as hand-edited: it
// existed before culi and must not be clobbered silently.
func fileStatus(path, rel string, desired []byte, man manifest) status {
	existing, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return needsWrite
	}
	if err != nil {
		return handEdited // unreadable ⇒ be conservative
	}
	if hashOf(existing) == hashOf(desired) {
		return upToDate
	}
	if prev, ok := man[rel]; !ok || hashOf(existing) != prev {
		return handEdited
	}
	return needsWrite
}

// staleStatus classifies a manifest entry whose card no longer exists.
func staleStatus(path, wantHash string) status {
	existing, err := os.ReadFile(path)
	if err != nil {
		return missing
	}
	if hashOf(existing) == wantHash {
		return upToDate
	}
	return handEdited
}

func readManifest(path string) (manifest, error) {
	man := manifest{}
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return man, nil
	}
	if err != nil {
		return nil, fmt.Errorf("export: reading manifest: %w", err)
	}
	if err := json.Unmarshal(raw, &man); err != nil {
		return nil, fmt.Errorf("export: decoding manifest %s: %w", path, err)
	}
	return man, nil
}

func writeManifest(path string, man manifest) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("export: creating state dir: %w", err)
	}
	raw, err := json.MarshalIndent(man, "", "  ")
	if err != nil {
		return fmt.Errorf("export: encoding manifest: %w", err)
	}
	return writeAtomic(path, raw)
}

// writeAtomic writes via temp file + rename so a crash never leaves a
// half-written generated file.
func writeAtomic(path string, raw []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("export: creating %s: %w", filepath.Dir(path), err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".culi-*")
	if err != nil {
		return fmt.Errorf("export: temp file for %s: %w", path, err)
	}
	if _, err := tmp.Write(raw); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return fmt.Errorf("export: writing %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("export: closing %s: %w", path, err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("export: replacing %s: %w", path, err)
	}
	return nil
}

func hashOf(raw []byte) string {
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
